### ISSUE TITLE
first version here

### ISSUE THREAD

**Issue by andreakoelzsch** [movestore/Movebank-Loc-move2#1]
Hi @annescharf ,
Hier mal die erste Zusammenstellung für die neue Movebank App. Dies ist ja auch direkt ein Test des neuen SDK...
Lokal läuft der Code, wenn ich ihn Schritt für Schritt in RFUnction.R laufen lasse, aber nicht im skd.R (wie es doch gedacht ist - siehe developer_readme). Die Datei configuration.json musste ich noch anpassen, aber ich finde den weg nicht für das passwort aus .env zu holen. (Movebank passwort ist schon updated, dieses hier funktioniert nicht mehr). Das kann ich lokal einfach mal reinschreiben, aber data=null in der Datei .env wird nicht akzeptiert... auch {} oder NULL nimmt es nicht... @cleemansen ?

hier der Fehler von sdk.R:
[DEBUG] Read input of type 'move::moveStack'
[DEBUG] sourceFile: null
[1] "ERROR:  Error in if (file.info(sourceFile)$size == 0) {: missing value where TRUE/FALSE needed\n"
[DEBUG] errorFile: ./data/output/error.log
[DEBUG] Writing to file ./data/output/error.log

**Comment by cleemansen** [comment]
> Schritt für Schritt in RFUnction.R laufen lasse, aber nicht im skd.R (wie es doch gedacht ist - siehe developer_readme

Ja - es soll per `skd.R` laufen. Das ist aus meiner Sicht komfortabler

> Die Datei configuration.json musste ich noch anpassen, aber ich finde den weg nicht für das passwort aus .env zu holen.

Das ist nochmal ein Spezialfall (Geheimnisse sicher lokal ablegen und nicht ausversehen ins GH pushn). Den muss ich noch zur Verfügung stellen

> [1] "ERROR: Error in if (file.info(sourceFile)$size == 0) {: missing value where TRUE/FALSE needed\n"

Auch hier nochmal ein Spezialfall - die Movebank-App ist eine App ohne Input-File (es ist eine Data-Source). Die meisten Apps erwarten eine File als ihr Input. Muss ich anpassen (wahrscheinlich eher hier in der App und nicht im Template)

**Comment by cleemansen** [comment]
> die Movebank-App ist eine App ohne Input-File

Auch das ist nicht die ganze Wahrheit - die Movebank-App besitzt das Feature Daten zu "mergen". D.h. sie kann ein Input-File herhalten - muss aber nicht!

**Comment by cleemansen** [comment]
> [1] "ERROR: Error in if (file.info(sourceFile)$size == 0) {: missing value where TRUE/FALSE needed\n"

Ich kann diesen Fehlerfall gerade gar nicht reproduzieren. Mit der Einstellung `SOURCE_FILE=` in `.env` wird es wie erwartet behandelt:

```
[DEBUG] sourceFile: 
[DEBUG] Skip loading: no source File
```

**Comment by cleemansen** [comment]
Thema Geheimnisse: ich habe es umgebaut dass es wieder so funktioniert wie in der move1 Movebank App

1. bitte erstelle bei dir die Datei `akoelzsch.env`
2. diese Datei ist in der `.gitignore` - sie verlässt also nicht die lokale Entwicklungsumgebung
3. Inhalt dieser Datei ist
```
# SECRETS
MOVEBANK_USERNAME=real-value
MOVEBANK_PASSWORD=real-value
```

**Comment by andreakoelzsch** [comment]
Danke für alle Anpassungen für diese SpezialApp @cleemansen! Nach ein paar Anpassungen im RFUnction.R läuft es jetzt lokal mit dem sdk.R. Mein Problem war, dass ich im `.env` `SOURCE_FILE = null` eingegeben hatte und es nicht freigelassen... Wegen dem Moevbank Passwort da war ich wieder mal zu unbedacht im pushen (aber alles geändert und gefixed), ich dachte es geht auch irgendwie in der.json die details reinzuholen, aber über den dotenv im sdk.R direkt ist wohl die beste Lösung hier, danke!

**Comment by andreakoelzsch** [comment]
Hi @annescharf, jetzt ist es wohl bereit für Änderungen und Verbesserungen...
