### ISSUE TITLE
List Animal IDs in order in the "Overview" panel

### ISSUE THREAD

**Issue by sarahcd** [movestore/Movebank-Loc-move2#22]
Under View > Settings, and in the final step of configuring the Movebank Location App, animals appear to be listed in a random order. Better to list in alphabetical order.

<img width="697" alt="image" src="https://github.com/movestore/Movebank-Loc-move2/assets/15783614/72e9819f-b163-4e6f-88a6-8b27da1b2597">

Might also apply to 
* "Configure Data Source Settings" for shared workflows?
* Movebank Non-location App?

**Comment by annescharf** [comment]
v2.2 of Movebank Location App orders the Animal names
