### ISSUE TITLE
Allow tracks based on local deployment ID

### ISSUE THREAD

**Issue by sarahcd** [movestore/Movebank-Loc-move2#24]
Where tracks are defined by deployment rather than animal, allow them to be named by the local_deployment_identifier from Movebank if the owner has provided this.

For an example use case, see the Gagliardo et al. (2022) example here:
https://github.com/movestore/Movebank_Example_Datasets?tab=readme-ov-file#working-with-deployed-data

Here the deployments represent experimental runs and the names indicate the animal, deployment site and experimental group.

The problem here is that it won't work if the owners hasn't defined their deployment IDs. Instructions to do it are here:
https://www.movebank.org/cms/movebank-content/upload-qc#add_deployments_and_reference_data

If there is no local_deployment_identifier, the internal deployment id from Movebank or the current naming scheme used by this App could be used.

**Comment by andreakoelzsch** [comment]
this gives an error presently, but is in the options and will work with the next update of move2
