### ISSUE TITLE
Specify Data Resolution

### ISSUE THREAD

**Issue by sarahcd** [movestore/Movebank-Loc-move2#25]
The Data Resolution option doesn't specify whether the thinning is done on the entire dataset, each animal, each deployment, etc.
Does the thinning account for whether location coordinates (positions) are present in the record?
Wording will depend on how tracks are defined in the App.

<img width="470" alt="image" src="https://github.com/movestore/Movebank-Loc-move2/assets/15783614/086f0710-3732-46ce-ab73-abd00efc0b1a">

"(selection of first location per interval)" is also not clear. What is an interval, and is the first record retained, or the first record containing location coordinates? I suspect it means "The first record per track will be retained." (replacing track with the correct term).

**Comment by andreakoelzsch** [comment]
@sarahcd this Movebank location App does allow only for location data, so that is not an issues here. For the clarity of thinning per track, here a suggestion for rewording:
"resolution in tracks thinned to one position per" ...  ("first record per segment will be retained")

**Comment by sarahcd** [comment]
For the location data, I meant whether the thinning could retain events that have empty location coordinates (no fix obtained), or only thin based on events that have location coordinates.

**Comment by andreakoelzsch** [comment]
If I am correct, Anne has made the code in a way to remove empty locations anyway.
