### ISSUE TITLE
Track data attributes **sometimes** not correctly formatted when using animal id as track id

### ISSUE THREAD

**Issue by smthfrmn** [movestore/Movebank-Loc-move2#30]
This may be related to #22 

Not sure exactly what the case is, but have found that sometimes when we load data from movebank and have the animal id set as the track id, the track attribute data contains lists in the columns. I assume this is because for some animals, they actually have multiple tracks. Not sure what the preferred behavior is, but the unconventional data format breaks other apps that are not expecting track attribute data to have lists. 

@annescharf can send you an example, if you need

**Comment by andreakoelzsch** [comment]
Hi @smthfrmn , you found exactly the point of many discussions and thinking Anne has had and we need to find a solution for. What would you suggest as a solution/expected behaviour of the object if there are more than one trackid for an animalid (and the tracks are defined by animalid)?

**Comment by annescharf** [comment]
Hi @smthfrmn, this error is the same as https://github.com/movestore/rds2csv/issues/13. The situation arises when one individual has several deployments, and in each deployment things change, e.g. age, weight, tag manufacturer, etc. We have had quite some discussions how to deal with it in move2 (https://gitlab.com/bartk/move2/-/issues/18, https://gitlab.com/bartk/move2/-/issues/72), its a tricky one. With the list solution it enables to e.g. split the tracks by deployment, and each deployment gets assigned the correct age, weight,etc. 
I've had a chat with Bart (https://gitlab.com/bartk/move2/-/issues/78) how to find a solution for some of the Apps in MoveApps, but I haven't had the time yet to code up the final solution. Once I do, I'll add it to the documentation, and let all developers know.
